Repository KusionStack/kusion, pull requests merged in 2022-06, with the labels that each got.

#64 bugfix: runtime apply and detail prompt cancel unexpectly
  pkg/engine/operation/change.go
  pkg/engine/operation/preview.go
  pkg/engine/operation/preview_test.go
  pkg/engine/operation/resource_node.go
  pkg/engine/operation/types.go
  pkg/engine/runtime/kubernetest_runtime.go
  pkg/kusionctl/cmd/apply/options.go
  pkg/kusionctl/cmd/apply/options_test.go
  pkg/kusionctl/cmd/destroy/options.go
  pkg/kusionctl/cmd/destroy/options_test.go
Labels: cli, engine, priority/critical-urgent

#69 chore: update CODEOWNERS and remove unused files
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci

#70 fix unit test for pkg/scaffold/internal
  pkg/scaffold/external_templates_test.go
Labels: testing

#71 chore: replace account id with dev team id
  .github/CODEOWNERS
Labels: ci

#73 add new FiledType: MapField and AnyField to indicate map entry and interface{}
  pkg/kusionctl/cmd/init/options.go
  pkg/scaffold/external_templates.go
  pkg/scaffold/external_templates_test.go
  pkg/scaffold/internal/deployment-single-stack/kusion.yaml
  pkg/scaffold/project.go
Labels: cli, optimization

#62 feat: support custom writer and storage for apply and preview
  go.mod
  go.sum
  pkg/engine/states/db_state.go
  pkg/engine/states/filesystem_state.go
  pkg/engine/states/oss_state.go
  pkg/engine/states/s3_state.go
  pkg/kusionctl/cmd/apply/options.go
  pkg/kusionctl/cmd/apply/options_test.go
Labels: cli, optimization

#68 remove pulumi deplendency, use third_party instead
  go.mod
  go.sum
  pkg/kusionctl/cmd/init/options.go
  pkg/projectstack/project.go
  pkg/projectstack/stack.go
  pkg/scaffold/external_templates.go
  pkg/scaffold/external_templates_test.go
  pkg/scaffold/loader.go
  third_party/pulumi/fsutil/walkup.go
  third_party/pulumi/gitutil/git.go
  third_party/pulumi/workspace/templates.go
Labels: optimization

#74 feat: kusion init support custom params body in JSON string, replace default value in kusion.yaml of specified template
  pkg/kusionctl/cmd/init/init.go
  pkg/kusionctl/cmd/init/options.go
  pkg/kusionctl/cmd/init/options_test.go
  pkg/scaffold/external_templates.go
  pkg/scaffold/external_templates_test.go
  pkg/scaffold/project.go
  pkg/scaffold/project_test.go
Labels: feature, cli

#76 chore: update readme of third party
  third_party/README.md
Labels: documentation

#81 State: add HTTPState as a new StateStorage
  go.sum
  pkg/engine/states/http_state.go
  pkg/engine/states/http_state_test.go
Labels: engine
