Repository KusionStack/kusion, pull requests merged in 2022-11, with the labels that each got.

#157 feat: warn when kusion is out of date
  go.mod
  go.sum
  pkg/kusionctl/cmd/cmd.go
  pkg/kusionctl/cmd/cmd_test.go
  pkg/util/kfile/file.go
Labels: feature, cli

#160 chore: bump kclvm-go version to v0.4.4-alpha.1
  go.mod
  go.sum
Labels: release

#176 feat: watch dependents and print them with new console UI
  pkg/engine/operation/watch.go
  pkg/engine/operation/watch_test.go
  pkg/engine/printers/table.go
  pkg/engine/runtime/kubernetes_runtime.go
  pkg/engine/runtime/runtime.go
Labels: feature, area/cli, area/runtime

#177 fix: empty resources in stack will generate panic
  go.mod
  go.sum
  pkg/kusionctl/cmd/apply/options.go
  pkg/kusionctl/cmd/preview/options.go
Labels: bug

#181 kusion watch: filter out unchanged resources
  pkg/kusionctl/cmd/apply/options.go
Labels: area/cli

#182 kusion watch: refine k8s resource relation
  pkg/engine/runtime/kubernetes_runtime.go
Labels: optimization, area/runtime
