Repository KusionStack/kusion, pull requests merged in 2022-08, with the labels that each got.

#106 feat: support k8s crd in kusion apply and kusion destroy
  pkg/compile/compile.go
  pkg/compile/compile_test.go
  pkg/compile/testdata/crd/foo.yaml
  pkg/resources/crd/crd.go
  pkg/resources/crd/crd_test.go
  pkg/resources/crd/testdata/multi.yaml
  pkg/resources/crd/testdata/one.yaml
  pkg/resources/visitor.go
Labels: feature, cli

#108 bugfix: resource nodes of delete action don't need compute action type again
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/operation/graph/resource_node_test.go
  pkg/engine/operation/preview_test.go
Labels: bug, engine

#107 bugfix: save unchanged but lived resource
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/operation/models/operation_context.go
Labels: bug, engine

#111 bugfix: invalid argument for "-D, --argument" flag: parse error, bare " in non-quoted-field
  pkg/kusionctl/cmd/apply/apply.go
  pkg/kusionctl/cmd/compile/compile.go
  pkg/kusionctl/cmd/destroy/destroy.go
Labels: cli

#118 bugfix: fix kclvm binary source dir of dockerfile
  Dockerfile
Labels: ci

#121 bugfix: copy kusionCLI to tar ball
  Makefile
Labels: ci

#119 chore: fix version format to match semantic versioning 2.0.0
  pkg/version/types.go
  pkg/version/types_test.go
Labels: cli

#124 feat: support kusion state remote storage
  docs/backend.md
  pkg/engine/backend/backend.go
  pkg/engine/backend/backend_test.go
  pkg/engine/backend/init/init.go
  pkg/engine/states/backend.go
  pkg/engine/states/local/backend.go
  pkg/engine/states/local/backend_test.go
  pkg/engine/states/local/filesystem_state.go
  pkg/engine/states/local/filesystem_state_test.go
  pkg/engine/states/remote/db_state.go
  pkg/kusionctl/cmd/apply/apply.go
  pkg/kusionctl/cmd/apply/options.go
  pkg/kusionctl/cmd/destroy/destroy.go
  pkg/kusionctl/cmd/destroy/options.go
  pkg/kusionctl/cmd/destroy/options_test.go
  pkg/projectstack/types.go
Labels: engine, state

#128 bugfix: set progressbar width to 0 manually, pterm will use terminal width
  pkg/kusionctl/cmd/apply/options.go
Labels: cli

#127 feat: kusion support apply CRD and CR at the same time
  go.mod
  go.sum
  pkg/engine/runtime/kubernetes_runtime.go
Labels: cli, runtime

#132 feat: kusion apply support ServerSide preview
  pkg/engine/runtime/kubernetes_runtime.go
Labels: runtime
