Repository KusionStack/kusion, pull requests merged in 2023-12, with the labels that each got.

#644 chore: rename ProjectConfiguration to Configuration to follow go convention
  pkg/apis/project/project.go
  pkg/apis/project/project_test.go
  pkg/apis/project/types.go
  pkg/apis/project/types_test.go
  pkg/cmd/apply/options_test.go
  pkg/cmd/build/builders/appconfig_builder_test.go
  pkg/cmd/build/options_test.go
  pkg/cmd/build/util_test.go
  pkg/cmd/destroy/options_test.go
  pkg/cmd/preview/options_test.go
  pkg/engine/operation/apply_test.go
  pkg/engine/operation/destory_test.go
  pkg/engine/operation/models/change_test.go
  pkg/engine/operation/preview_test.go
  pkg/modules/generators/accessories/database/alicloud_rds_test.go
  pkg/modules/generators/accessories/database/aws_rds_test.go
  pkg/modules/generators/accessories/database/database_generator_test.go
  pkg/modules/generators/accessories/database/local_database_test.go
  pkg/modules/generators/app_configurations_generator_test.go
  pkg/modules/generators/monitoring/monitoring_generator.go
  pkg/modules/generators/monitoring/monitoring_generator_test.go
  pkg/modules/generators/trait/ops_rule_generator_test.go
  pkg/modules/generators/workload/job_generator_test.go
  pkg/modules/generators/workload/secret/secret_generator_test.go
  pkg/modules/generators/workload/service_generator_test.go
  pkg/modules/generators/workload/workload_generator_test.go
  pkg/modules/patchers/monitoring/monitoring_patcher.go
  pkg/modules/patchers/monitoring/monitoring_patcher_test.go
Labels: kind/optimization

#645 chore: rename ExternalSecretRef key to name
  pkg/apis/secrets/types.go
  pkg/secrets/providers/hashivault/vault.go
  pkg/secrets/providers/hashivault/vault_test.go
Labels: kind/optimization

#642 feat: add workspace, modules, backends, runtimes management
  pkg/apis/workspace/backends.go
  pkg/apis/workspace/modules.go
  pkg/apis/workspace/runtimes.go
  pkg/apis/workspace/types.go
  pkg/apis/workspace/workspace.go
  pkg/workspace/util.go
  pkg/workspace/util_test.go
  pkg/workspace/validation.go
  pkg/workspace/validation_test.go
Labels: kind/feature

#599 docs: add secret management proposal
  docs/design/secrets_management/secret_management.md
  docs/design/secrets_management/workflow.png
Labels: proposal

#623 feat: add aws secrets manager based secret store provider
  go.mod
  go.sum
  pkg/secrets/providers/aws/auth/auth.go
  pkg/secrets/providers/aws/secretsmanager/fake/fake.go
  pkg/secrets/providers/aws/secretsmanager/interface.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
Labels: kind/feature

#658 fix: job generator missing pod restartPolicy issue
  pkg/modules/generators/workload/job_generator.go
Labels: kind/bug

#679 chore: delete useless gitutil types
  pkg/util/gitutil/types.go
Labels: kind/cleanup

#680 feat: update command constructor and enable profiling
  go.mod
  go.sum
  hack/gen-docs/main.go
  kusion.go
  pkg/cmd/cmd.go
  pkg/cmd/profiling.go
Labels: kind/enhancement

#677 refactor: update secret store providers implementation
  pkg/secrets/providers.go
  pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
  pkg/secrets/providers/hashivault/vault.go
  pkg/secrets/providers/register/register.go
  pkg/secrets/providers_test.go
Labels: kind/optimization

#704 feat: support customize namespace through workspace config
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/namespace_generator.go
  pkg/modules/generators/namespace_generator_test.go
Labels: kind/feature

#652 feat: add azure keyvault based secret store
  go.mod
  go.sum
  pkg/apis/secrets/types.go
  pkg/secrets/providers/azure/keyvault/fake/fake.go
  pkg/secrets/providers/azure/keyvault/interface.go
  pkg/secrets/providers/azure/keyvault/keyvault.go
  pkg/secrets/providers/azure/keyvault/keyvault_test.go
Labels: kind/feature

#707 chore: cleanup useless io util code
  pkg/util/io/file.go
  pkg/util/io/io.go
  pkg/util/io/io_test.go
Labels: kind/cleanup

#712 chore: secret generator add more comments
  pkg/modules/generators/workload/secret/secret_generator.go
Labels: kind/optimization

#710 refactor: re-pack basic api types for susitable iteration
  pkg/apis/core/group.go
  pkg/apis/core/v1/intent.go
  pkg/apis/core/v1/types.go
  pkg/apis/core/v1/workspace.go
  pkg/apis/internal/group.go
  pkg/apis/internal/v1/types.go
Labels: kind/optimization

#713 refactor: use workspace types with v1 pkg
  pkg/apis/workspace/types.go
  pkg/cmd/build/builders/appconfig_builder.go
  pkg/cmd/build/builders/appconfig_builder_test.go
  pkg/cmd/build/util_test.go
  pkg/engine/backend/config.go
  pkg/engine/backend/config_test.go
  pkg/engine/backend/init/init.go
  pkg/engine/backend/options.go
  pkg/engine/backend/options_test.go
  pkg/engine/backend/util.go
  pkg/engine/backend/util_test.go
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/app_configurations_generator_test.go
  pkg/modules/generators/namespace_generator.go
  pkg/modules/generators/namespace_generator_test.go
  pkg/modules/util.go
  pkg/modules/util_test.go
  pkg/workspace/operator.go
  pkg/workspace/operator_test.go
  pkg/workspace/util.go
  pkg/workspace/util_test.go
  pkg/workspace/validation.go
  pkg/workspace/validation_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/optimization

#714 refactor: use secret types in core v1 pkg
  pkg/apis/core/v1/workspace.go
  pkg/apis/secrets/types.go
  pkg/secrets/interfaces.go
  pkg/secrets/providers.go
  pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
  pkg/secrets/providers/alicloud/secretsmanager/secretsmanager_test.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
  pkg/secrets/providers/azure/keyvault/keyvault.go
  pkg/secrets/providers/azure/keyvault/keyvault_test.go
  pkg/secrets/providers/hashivault/vault.go
  pkg/secrets/providers/hashivault/vault_test.go
  pkg/secrets/providers_test.go
Labels: kind/optimization

#721 fix: customize namespace generator issue
  pkg/modules/generators/accessories/database/alicloud_rds_test.go
  pkg/modules/generators/accessories/database/aws_rds_test.go
  pkg/modules/generators/accessories/database/database_generator.go
  pkg/modules/generators/accessories/database/database_generator_test.go
  pkg/modules/generators/accessories/database/local_database.go
  pkg/modules/generators/accessories/database/local_database_test.go
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/app_configurations_generator_test.go
  pkg/modules/generators/monitoring/monitoring_generator.go
  pkg/modules/generators/monitoring/monitoring_generator_test.go
  pkg/modules/generators/namespace_generator.go
  pkg/modules/generators/namespace_generator_test.go
  pkg/modules/generators/trait/ops_rule_generator.go
  pkg/modules/generators/trait/ops_rule_generator_test.go
  pkg/modules/generators/workload/job_generator.go
  pkg/modules/generators/workload/job_generator_test.go
  pkg/modules/generators/workload/network/ports_generator.go
  pkg/modules/generators/workload/network/ports_generator_test.go
  pkg/modules/generators/workload/secret/secret_generator.go
  pkg/modules/generators/workload/secret/secret_generator_test.go
  pkg/modules/generators/workload/service_generator.go
  pkg/modules/generators/workload/service_generator_test.go
  pkg/modules/generators/workload/workload_generator.go
  pkg/modules/generators/workload/workload_generator_test.go
  pkg/modules/inputs/appconfiguration.go
  pkg/modules/interfaces.go
  pkg/modules/types.go
Labels: kind/bug

#724 feat: update workspace api type add secret store config
  pkg/apis/core/v1/workspace.go
  pkg/workspace/validation.go
  pkg/workspace/validation_test.go
Labels: kind/feature, kind/enhancement
