Repository KusionStack/kusion, pull requests merged in 2023-11, with the labels that each got.

#602 feat: add random string function for upcoming secret generator refact
  pkg/generator/appconfiguration/generator/workload/secret/rand.go
  pkg/generator/appconfiguration/generator/workload/secret/rand_test.go
Labels: kind/enhancement

#609 refactor: deprecate old vals based secret store
  pkg/cmd/apply/options.go
  pkg/cmd/preview/options.go
  pkg/engine/operation/apply.go
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/operation/models/operation_context.go
  pkg/engine/operation/preview.go
  pkg/projectstack/types.go
  pkg/vals/doc.go
  pkg/vals/secret_stores.go
  pkg/vals/vals.go
Labels: kind/optimization, area/engine

#607 refactor: update secret generator for upcoming external secret
  pkg/generator/appconfiguration/generator/workload/secret/secret_generator.go
  pkg/generator/appconfiguration/generator/workload/secret/secret_generator_test.go
  pkg/generator/appconfiguration/generator/workload/secret_generator.go
  pkg/generator/appconfiguration/generator/workload/secret_generator_test.go
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/models/appconfiguration/workload/secret.go
Labels: kind/optimization, kind/enhancement

#610 feat: add external secret store api and interface
  pkg/apis/secrets/types.go
  pkg/secrets/interface.go
Labels: kind/feature, area/cli

#613 chore: delete redundant scripts
  Makefile
  hack/md5file/main.go
  scripts/install-kcl-go/main.go
  scripts/install-kcl-openapi/go.mod
  scripts/install-kcl-openapi/go.sum
  scripts/install-kcl-openapi/main.go
  third_party/README.md
Labels: kind/cleanup

#612 feat: add secret store provider registry impl
  pkg/secrets/interfaces.go
  pkg/secrets/providers.go
  pkg/secrets/providers_test.go
Labels: kind/feature

#615 fix: stack nil pointer error
  pkg/engine/operation/watch.go
Labels: kind/bug, area/cli

#624 feat: update secrets related types and interfaces
  pkg/apis/secrets/types.go
  pkg/secrets/interfaces.go
  pkg/secrets/providers.go
  pkg/secrets/providers_test.go
Labels: kind/feature

#614 feat: add vault secret store impl
  go.mod
  go.sum
  pkg/apis/secrets/types.go
  pkg/secrets/providers.go
  pkg/secrets/providers/hashivault/fake/fake.go
  pkg/secrets/providers/hashivault/interface.go
  pkg/secrets/providers/hashivault/vault.go
  pkg/secrets/providers/hashivault/vault_test.go
Labels: kind/feature
