Repository KusionStack/kusion, pull requests merged in 2023-09, with the labels that each got.

#504 feat: support config maxunavaliable in deployment
  pkg/generator/appconfiguration/generator/app_configurations_generator.go
  pkg/generator/appconfiguration/generator/workload/service_generator.go
  pkg/generator/appconfiguration/generator/workload/service_generator_test.go
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
Labels: kind/feature

#512 fix: set host to empty when url parse get localhost or 127.0.0.1
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
Labels: kind/bug, area/cli

#505 feat: update scaffold template with kpm
  go.mod
  go.sum
  pkg/cmd/apply/options.go
  pkg/cmd/compile/options.go
  pkg/cmd/preview/options.go
  pkg/generator/generator.go
  pkg/generator/kcl/kcl_generator.go
  pkg/scaffold/internal/deployment-single-stack/README.md
  pkg/scaffold/internal/deployment-single-stack/base/base.k
  pkg/scaffold/internal/deployment-single-stack/dev/ci-test/settings.yaml
  pkg/scaffold/internal/deployment-single-stack/dev/kcl.yaml
  pkg/scaffold/internal/deployment-single-stack/dev/main.k
  pkg/scaffold/internal/deployment-single-stack/kusion.yaml
  pkg/scaffold/internal/deployment-single-stack/project.yaml
  pkg/scaffold/internal/single-stack-sample/README.md
  pkg/scaffold/internal/single-stack-sample/dev/kcl.mod
  pkg/scaffold/internal/single-stack-sample/dev/kcl.mod.lock
  pkg/scaffold/internal/single-stack-sample/dev/main.k
  pkg/scaffold/internal/single-stack-sample/dev/stack.yaml
  pkg/scaffold/internal/single-stack-sample/kusion.yaml
  pkg/scaffold/internal/single-stack-sample/project.yaml
  pkg/scaffold/internal_templates_test.go
  pkg/scaffold/templates_test.go
Labels: kind/feature, area/cli

#543 Docs: CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
Labels: kind/documentation

#559 fix: wrong e2e test as new konfig dir
  test/e2e/kusionctl_test.go
Labels: area/testing

#560 fix: wrong e2e test again
  test/e2e/kusionctl_test.go
Labels: area/testing

#562 fix: the issue of failing to parse spec file
  pkg/cmd/preview/options.go
  pkg/cmd/spec/generator.go
  pkg/cmd/spec/generator_test.go
Labels: kind/bug
