Repository KusionStack/kusion, pull requests merged in 2023-08, with the labels that each got.

#421 refactor: refine generator to make it more extensible
  pkg/generator/app_configuration/app_config_generator.go
  pkg/generator/app_configuration/generators/app_configuration_generator.go
  pkg/generator/app_configuration/generators/components_generator.go
  pkg/generator/app_configuration/generators/deployment_generator.go
  pkg/generator/app_configuration/generators/job_generator.go
  pkg/generator/app_configuration/generators/namespace_generator.go
  pkg/generator/app_configuration/generators/types.go
  pkg/generator/app_configuration/generators/util.go
  pkg/generator/app_configuration/util.go
Labels: kind/optimization

#422 fix: some lint and style problems
  pkg/cmd/destroy/options_test.go
  pkg/cmd/preview/options_test.go
  pkg/cmd/spec/generator.go
  pkg/cmd/spec/generator_test.go
  pkg/engine/operation/apply_test.go
  pkg/engine/operation/destory_test.go
  pkg/engine/operation/graph/resource_node_test.go
  pkg/engine/operation/parser/spec_parser_test.go
  pkg/engine/operation/preview_test.go
  pkg/engine/operation/watch_test.go
  pkg/generator/appconfiguration/app_config_generator.go
  pkg/generator/appconfiguration/generators/app_configuration_generator.go
  pkg/generator/appconfiguration/generators/components_generator.go
  pkg/generator/appconfiguration/generators/deployment_generator.go
  pkg/generator/appconfiguration/generators/job_generator.go
  pkg/generator/appconfiguration/generators/namespace_generator.go
  pkg/generator/appconfiguration/generators/types.go
  pkg/generator/appconfiguration/generators/util.go
  pkg/generator/kcl/kcl_generator_test.go
Labels: kind/optimization

#427 feat: implement deployment generator
  pkg/generator/appconfiguration/generators/components_generator.go
  pkg/generator/appconfiguration/generators/deployment_generator.go
  pkg/generator/appconfiguration/generators/namespace_generator.go
  pkg/generator/appconfiguration/generators/util.go
Labels: kind/feature

#428 refactor: use ordered map for component and container
  pkg/generator/appconfiguration/generators/components_generator.go
  pkg/generator/appconfiguration/generators/deployment_generator.go
  pkg/generator/appconfiguration/generators/util.go
Labels: kind/optimization

#439 feat: add job generator
  pkg/generator/appconfiguration/generators/components_generator.go
  pkg/generator/appconfiguration/generators/deployment_generator.go
  pkg/generator/appconfiguration/generators/job_generator.go
  pkg/generator/appconfiguration/generators/job_generator_test.go
  pkg/generator/appconfiguration/generators/util.go
  pkg/models/appconfiguration/component/component.go
  pkg/models/appconfiguration/component/job/job.go
  pkg/models/appconfiguration/component/workload/job.go
  pkg/models/appconfiguration/component/workload/long_running_service.go
Labels: kind/feature, priority/important-soon, runtime/k8s

#412 doc: Add design documentation for Prometheus support in kusion
  docs/prometheus.md
Labels: kind/documentation, kind/enhancement

#449 refactor: Use mock as the function name instead of monkey
  pkg/cmd/preview/options_test.go
Labels: kind/cleanup

#448 feat: remove mandatory validation of settings.yaml during kusion compile
  pkg/cmd/check/check_test.go
  pkg/cmd/compile/compile.go
  pkg/cmd/compile/compile_test.go
  pkg/cmd/compile/options.go
  pkg/cmd/compile/options_test.go
Labels: kind/feature

#453 feat: modify the generators to adapt to the new model's adjustments
  pkg/cmd/spec/generator.go
  pkg/generator/appconfiguration/app_configurations_generator.go
  pkg/generator/appconfiguration/generators/app_configuration_generator.go
  pkg/generator/appconfiguration/generators/components_generator.go
  pkg/generator/appconfiguration/generators/deployment_generator.go
  pkg/generator/appconfiguration/generators/job_generator.go
  pkg/generator/appconfiguration/generators/job_generator_test.go
  pkg/generator/appconfiguration/generators/util.go
  pkg/generator/appconfiguration/generators/workload_generator.go
  pkg/generator/appconfiguration/generators/workload_service_generator.go
  pkg/models/appconfiguration/appconfiguration.go
  pkg/models/appconfiguration/component/component.go
  pkg/models/appconfiguration/component/workload/job.go
  pkg/models/appconfiguration/component/workload/long_running_service.go
  pkg/models/appconfiguration/workload/common.go
  pkg/models/appconfiguration/workload/container/container.go
  pkg/models/appconfiguration/workload/job.go
  pkg/models/appconfiguration/workload/service.go
  pkg/models/appconfiguration/workload/workload.go
Labels: kind/enhancement

#455 refactor: use generic optimization code
  pkg/generator/appconfiguration/app_configurations_generator.go
  pkg/generator/appconfiguration/generators/util.go
  pkg/generator/appconfiguration/generators/workload_service_generator.go
Labels: kind/optimization

#485 feat: support default order of kubernetes resource
  pkg/generator/appconfiguration/generator/app_configurations_generator.go
  pkg/generator/appconfiguration/generator/ordered_resources_generator.go
  pkg/generator/appconfiguration/generator/ordered_resources_generator_test.go
Labels: kind/feature

#487 feat: add probe types and encoding/decoding support
  pkg/models/appconfiguration/workload/container/container.go
  pkg/models/appconfiguration/workload/container/container_test.go
Labels: kind/feature

#491 feat: add lifecycle type and encoding/decoding support
  pkg/models/appconfiguration/workload/container/container.go
  pkg/models/appconfiguration/workload/container/container_test.go
Labels: kind/feature

#492 refactor: replace cmd arguments from string array to map
  pkg/cmd/apply/options.go
  pkg/cmd/check/check_test.go
  pkg/cmd/compile/compile.go
  pkg/cmd/compile/compile_test.go
  pkg/cmd/compile/options.go
  pkg/cmd/deps/deps_test.go
  pkg/cmd/deps/options.go
  pkg/cmd/destroy/options.go
  pkg/cmd/diff/diff_test.go
  pkg/cmd/diff/options.go
  pkg/cmd/env/options.go
  pkg/cmd/init/options.go
  pkg/cmd/init/options_test.go
  pkg/cmd/ls/options.go
  pkg/cmd/ls/options_test.go
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
  pkg/cmd/preview/preview.go
  pkg/cmd/util/helpers.go
  pkg/cmd/util/helpers_test.go
  pkg/engine/operation/watch.go
  pkg/generator/generator.go
  pkg/generator/kcl/kcl_generator.go
  pkg/generator/kcl/kcl_generator_test.go
Labels: kind/optimization

#494 feat: add a ruleset generator to support the maxavailable deploy strategy.
  pkg/generator/appconfiguration/generator/trait/ops_rule_generator.go
  pkg/generator/appconfiguration/generator/trait/ops_rule_generator_test.go
  pkg/generator/appconfiguration/generator/workload/service_generator.go
  pkg/models/appconfiguration/appconfiguration.go
  pkg/models/appconfiguration/appconfiguration_test.go
  pkg/models/appconfiguration/trait/ops_rule.go
  pkg/models/appconfiguration/workload/service.go
Labels: kind/enhancement

#495 feat: update workload generator support probe&lifecycle
  go.mod
  go.sum
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
  pkg/models/appconfiguration/workload/common.go
  pkg/util/net/parse.go
  pkg/util/net/parse_test.go
Labels: kind/feature

#479 feat: support creating files with configmap in container
  pkg/generator/appconfiguration/generator/workload/job_generator.go
  pkg/generator/appconfiguration/generator/workload/service_generator.go
  pkg/generator/appconfiguration/generator/workload/service_generator_test.go
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
Labels: kind/feature

#501 fix: port in probe url now gets parsed properly
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
Labels: kind/bug

#490 feat: add Prometheus support
  go.mod
  go.sum
  pkg/generator/appconfiguration/generator/app_configurations_generator.go
  pkg/generator/appconfiguration/generator/monitoring_generator.go
  pkg/generator/appconfiguration/generator/monitoring_generator_test.go
  pkg/generator/appconfiguration/generator/workload/service_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator.go
  pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
  pkg/models/appconfiguration/appconfiguration.go
  pkg/models/appconfiguration/monitoring/monitoring.go
  pkg/projectstack/types.go
Labels: kind/enhancement
