Repository KusionStack/kusion, pull requests merged in 2023-07, with the labels that each got.

#364 chore: bump kcl version to the stable version v0.5.x and use the `kcl-lang.io/kcl-go` package path
  .github/workflows/release.yaml
  .golangci.yml
  .goreleaser.yml
  go.mod
  go.sum
  kusion.go
  pkg/cmd/deps/options.go
  pkg/engine/kcl.go
  pkg/generator/kcl/kcl_generator.go
  pkg/generator/kcl/kcl_generator_test.go
  pkg/generator/kcl/rest/model.go
  pkg/generator/kcl/rest/rest.go
  pkg/generator/kcl/type.go
  pkg/generator/kcl/type_test.go
  pkg/version/scripts/gen/gen.go
  pkg/version/types.go
  pkg/version/types_test.go
  scripts/install-kcl-go/main.go
Labels: area/release

#400 feat: support spec as input
  docs/cmd/en_US/kusion.md
  docs/cmd/en_US/kusion_apply.md
  docs/cmd/en_US/kusion_check.md
  docs/cmd/en_US/kusion_compile.md
  docs/cmd/en_US/kusion_deps.md
  docs/cmd/en_US/kusion_destroy.md
  docs/cmd/en_US/kusion_env.md
  docs/cmd/en_US/kusion_init.md
  docs/cmd/en_US/kusion_init_templates.md
  docs/cmd/en_US/kusion_ls.md
  docs/cmd/en_US/kusion_preview.md
  docs/cmd/en_US/kusion_version.md
  docs/cmd/zh_CN/kusion.md
  docs/cmd/zh_CN/kusion_apply.md
  docs/cmd/zh_CN/kusion_check.md
  docs/cmd/zh_CN/kusion_compile.md
  docs/cmd/zh_CN/kusion_deps.md
  docs/cmd/zh_CN/kusion_destroy.md
  docs/cmd/zh_CN/kusion_env.md
  docs/cmd/zh_CN/kusion_init.md
  docs/cmd/zh_CN/kusion_init_templates.md
  docs/cmd/zh_CN/kusion_ls.md
  docs/cmd/zh_CN/kusion_preview.md
  docs/cmd/zh_CN/kusion_version.md
  go.mod
  go.sum
  pkg/cmd/apply/apply.go
  pkg/cmd/apply/options.go
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
  pkg/cmd/preview/preview.go
  pkg/cmd/spec/generator.go
  pkg/cmd/spec/generator_test.go
  pkg/util/i18n/translations/kusion/en_US/LC_MESSAGES/kusion.po
  pkg/util/i18n/translations/kusion/template.pot
  pkg/util/i18n/translations/kusion/zh_CN/LC_MESSAGES/kusion.mo
  pkg/util/i18n/translations/kusion/zh_CN/LC_MESSAGES/kusion.po
Labels: kind/feature, priority/critical-urgent, kind/enhancement

#414 chore: bump kcl version to v0.5.1
  go.mod
  go.sum
Labels: area/release

#416 feat: add app configuration model in golang
  pkg/cmd/spec/generator.go
  pkg/generator/app_configuration/app_config_generator.go
  pkg/models/appconfiguration/appconfiguration.go
  pkg/models/appconfiguration/component/component.go
  pkg/models/appconfiguration/component/container/container.go
Labels: kind/optimization

#418 feat: add job type to generator
  pkg/cmd/compile/options_test.go
  pkg/models/appconfiguration/component/component.go
  pkg/models/appconfiguration/component/job/job.go
Labels: kind/feature, priority/important-longterm
