Repository KusionStack/kusion, pull requests merged in 2024-08, with the labels that each got.

#1247 feat: set module plugin working dir
  go.mod
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/plugin.go
Labels: kind/feature

#1251 fix: typo in destroy.go and destroy_test.go filenames
  pkg/engine/operation/destroy.go
  pkg/engine/operation/destroy_test.go
Labels: kind/optimization

#1252 fix: deep copy release to update when destroy
  pkg/cmd/destroy/destroy.go
Labels: kind/bug

#1257 feat: bump kpm to v0.9.5 and upgrade related dependencies
  go.mod
  go.sum
  pkg/cmd/mod/add.go
  pkg/engine/api/generate/generator/generator.go
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/app_configurations_generator_test.go
Labels: kind/feature

#1260 feat: remove requirement to use imported resource when apply
  pkg/engine/runtime/terraform/terraform_runtime.go
  pkg/modules/generators/app_configurations_generator.go
Labels: kind/feature

#1235 feat: add a new command kusion release list
  pkg/cmd/release/list.go
  pkg/cmd/release/list_test.go
  pkg/cmd/release/release.go
Labels: help wanted, kind/feature

#1265 feat: add kusion release show command
  pkg/cmd/release/release.go
  pkg/cmd/release/show.go
  pkg/cmd/release/show_test.go
Labels: kind/feature

#1268 feat: add KCL based customized health check
  pkg/apis/api.kusion.io/v1/types.go
  pkg/cmd/apply/apply.go
  pkg/cmd/apply/apply_test.go
  pkg/engine/printers/generate.go
  pkg/modules/generators/app_configurations_generator.go
  pkg/util/kcl/kcl.go
  pkg/util/kcl/kcl_test.go
Labels: kind/feature

#1275 fix: add rpc tag for builds in goreleaser
  .goreleaser.yml
  .goreleaser_informal.yml
Labels: kind/bug

#1279 fix: bugs of watching while apply
  pkg/cmd/apply/apply.go
Labels: kind/bug
