Repository KusionStack/kusion, pull requests merged in 2024-07, with the labels that each got.

#1197 test: add windows e2e test
  .github/workflows/e2e-test.yml
  Makefile
  docs/design/kusion_module/kusion_modules.md
  hack/run-e2e.sh
  test/e2e/e2e_suite_test.go
  test/e2e/kusionctl_test.go
Labels: area/test

#1211 feat: support runtime configurations in workspace
  pkg/apis/api.kusion.io/v1/types.go
  pkg/cmd/apply/apply.go
  pkg/engine/operation/apply.go
  pkg/engine/operation/apply_test.go
  pkg/engine/operation/destory.go
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/operation/graph/resource_node_test.go
  pkg/engine/operation/preview.go
  pkg/engine/operation/preview_test.go
  pkg/engine/operation/watch.go
  pkg/engine/operation/watch_test.go
  pkg/engine/release/util.go
  pkg/engine/runtime/init/init.go
  pkg/engine/runtime/kubernetes/kubeops/config.go
  pkg/engine/runtime/kubernetes/kubernetes_runtime.go
  pkg/engine/runtime/terraform/terraform_runtime.go
  pkg/engine/runtime/terraform/tfops/workspace.go
  pkg/modules/generators/app_configurations_generator.go
Labels: kind/feature

#1219 fix: locked release file caused by interruption
  pkg/cmd/destroy/destroy.go
  pkg/cmd/destroy/destroy_test.go
  pkg/engine/operation/models/change.go
Labels: kind/bug

#1216 fix: deep copy resource attributes
  pkg/util/diff/diff.go
Labels: kind/bug

#1227 feat: mask sensitive data before printing the preview changes
  pkg/cmd/preview/preview.go
  pkg/util/diff/diff.go
  pkg/util/diff/diff_test.go
Labels: kind/feature

#1233 feat: support preview all details with flag
  pkg/cmd/preview/preview.go
Labels: kind/feature

#1234 fix: a bug of getting kubeconfig client
  pkg/engine/runtime/kubernetes/kubeops/config.go
  pkg/engine/runtime/kubernetes/kubernetes_runtime.go
Labels: kind/bug

#1238 feat: support imported resources
  pkg/apis/api.kusion.io/v1/types.go
  pkg/engine/operation/graph/resource_node.go
  pkg/modules/generators/app_configurations_generator.go
Labels: kind/feature

#1244 fix: duplicate equal sign in mod push cmd comments
  pkg/cmd/mod/push.go
Labels: kind/cleanup
