Repository KusionStack/kusion, pull requests merged in 2024-12, with the labels that each got.

#1333 refactor: appconfig and module generators
  go.mod
  go.sum
  pkg/engine/api/builders/appconfig_builder.go
  pkg/engine/api/builders/appconfig_builder_test.go
  pkg/generators/appconfiguration/app_configurations_generator.go
  pkg/generators/appconfiguration/app_configurations_generator_test.go
  pkg/generators/doc.go
  pkg/generators/interfaces.go
  pkg/generators/namespace/namespace_generator.go
  pkg/generators/namespace/namespace_generator_test.go
  pkg/generators/orderedresources/ordered_resources_generator.go
  pkg/generators/orderedresources/ordered_resources_generator_test.go
  pkg/generators/secret/rand.go
  pkg/generators/secret/rand_test.go
  pkg/generators/secret/secret.go
  pkg/generators/secret/secret_test.go
  pkg/generators/util.go
  pkg/generators/util_test.go
  pkg/modules/generators/namespace_generator.go
  pkg/modules/generators/ordered_resources_generator.go
  pkg/modules/interfaces.go
  pkg/modules/plugin.go
  pkg/modules/proto/module.pb.go
  pkg/modules/proto/module.proto
  pkg/modules/proto/module_grpc.pb.go
  pkg/modules/proto/scrip.sh
  pkg/modules/util.go
  pkg/workspace/validation.go
  pkg/workspace/validation_test.go
Labels: kind/optimization

#1346 test: wrap workspace unit tests into a suite
  .gitignore
  pkg/engine/runtime/terraform/tfops/test_data/.terraform.lock.hcl
  pkg/engine/runtime/terraform/tfops/test_data/main.tf.json
  pkg/engine/runtime/terraform/tfops/test_data/plan.out
  pkg/engine/runtime/terraform/tfops/test_data/terraform.tfstate
  pkg/engine/runtime/terraform/tfops/test_data/terraform.tfstate.backup
  pkg/engine/runtime/terraform/tfops/workspace_test.go
Labels: kind/bug, area/test

#1345 feat: add kusion mod login and pull sub-command
  go.mod
  go.sum
  pkg/cmd/generate/generate.go
  pkg/cmd/mod/login.go
  pkg/cmd/mod/mod.go
  pkg/cmd/mod/pull.go
  pkg/engine/api/generate/run/run.go
Labels: kind/feature

#1356 feat: support google cloud storage as backend
  go.mod
  go.sum
  pkg/apis/api.kusion.io/v1/types.go
  pkg/backend/backend.go
  pkg/backend/storages/google.go
  pkg/backend/storages/google_test.go
  pkg/engine/release/storages/google.go
  pkg/engine/release/storages/google_test.go
  pkg/engine/resource/graph/storages/google.go
  pkg/project/storages/google.go
  pkg/project/storages/google_test.go
  pkg/server/manager/workspace/util.go
  pkg/workspace/storages/google.go
  pkg/workspace/storages/google_test.go
Labels: kind/feature

#1363 fix: the problem of dependency change status not being updated
  pkg/apis/api.kusion.io/v1/resource.go
  pkg/engine/operation/graph/resource_node.go
Labels: kind/bug

#1365 fix: kusion server handler swagger apis
  api/openapispec/docs.go
  api/openapispec/swagger.json
  api/openapispec/swagger.yaml
  go.mod
  pkg/server/handler/backend/handler.go
  pkg/server/handler/module/handler.go
  pkg/server/handler/organization/handler.go
  pkg/server/handler/project/handler.go
  pkg/server/handler/resource/handler.go
  pkg/server/handler/source/handler.go
  pkg/server/handler/stack/execute.go
  pkg/server/handler/stack/execute_async.go
  pkg/server/handler/stack/handler.go
  pkg/server/handler/stack/run.go
  pkg/server/handler/workspace/configs.go
  pkg/server/handler/workspace/handler.go
Labels: kind/bug
