Repository KusionStack/kusion, pull requests merged in 2024-01, with the labels that each got.

#737 feat: secret generator support external secret type
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/workload/secret/secret_generator.go
  pkg/modules/generators/workload/secret/secret_generator_test.go
  pkg/modules/inputs/workload/secret.go
  pkg/modules/interfaces.go
  pkg/secrets/providers.go
  pkg/secrets/providers/register/register.go
Labels: kind/feature

#738 refactor: rename SecretStoreFactory to SecretStoreProvider
  pkg/secrets/interfaces.go
  pkg/secrets/providers.go
  pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
  pkg/secrets/providers/alicloud/secretsmanager/secretsmanager_test.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
  pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
  pkg/secrets/providers/azure/keyvault/keyvault.go
  pkg/secrets/providers/azure/keyvault/keyvault_test.go
  pkg/secrets/providers/hashivault/vault.go
  pkg/secrets/providers/hashivault/vault_test.go
  pkg/secrets/providers_test.go
Labels: kind/optimization

#739 feat: add fake secret store provider for test
  pkg/apis/core/v1/workspace.go
  pkg/secrets/interfaces.go
  pkg/secrets/providers/fake/fake.go
  pkg/secrets/providers/fake/fake_test.go
  pkg/secrets/providers/register/register.go
Labels: kind/feature

#740 chore: secret generator add more test cases
  pkg/modules/generators/app_configurations_generator.go
  pkg/modules/generators/workload/secret/secret_generator.go
  pkg/modules/generators/workload/secret/secret_generator_test.go
  pkg/modules/interfaces.go
Labels: area/testing

#771 fix: inaccurate action type when a live resource has been deleted
  pkg/engine/operation/graph/resource_node.go
Labels: kind/bug
