Repository KusionStack/kusion, pull requests merged in 2024-04, with the labels that each got.

#871 refactor: update api package for enhanced maintainability
  pkg/apis/api.kusion.io/group.go
  pkg/apis/api.kusion.io/v1/resource.go
  pkg/apis/api.kusion.io/v1/types.go
  pkg/apis/internal.kusion.io/group.go
  pkg/apis/internal.kusion.io/v1/marshal.go
  pkg/apis/internal.kusion.io/v1/marshal_test.go
  pkg/apis/internal.kusion.io/v1/types.go
  pkg/apis/internal.kusion.io/v1/unmarshal.go
  pkg/apis/internal.kusion.io/v1/unmarshal_test.go
Labels: area/cli, kind/optimization

#1005 feat: add meta flags and options for common logic and data
  go.mod
  go.sum
  pkg/cmd/apply/options.go
  pkg/cmd/apply/options_test.go
  pkg/cmd/cmd.go
  pkg/cmd/cmd_test.go
  pkg/cmd/destroy/options.go
  pkg/cmd/destroy/options_test.go
  pkg/cmd/generate/generate.go
  pkg/cmd/meta/meta.go
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
  pkg/project/paths.go
  pkg/project/paths_test.go
Labels: kind/feature

#1034 feat: adjust generate cmd behavior according to latest discussion
  pkg/cmd/apply/options.go
  pkg/cmd/apply/options_test.go
  pkg/cmd/build/builders/doc.go
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generator/generator.go
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
Labels: kind/feature, area/cli

#1006 refactor: preview&apply cmd implementation follow the command cmd pattern
  pkg/cmd/apply/apply.go
  pkg/cmd/apply/apply_test.go
  pkg/cmd/apply/options.go
  pkg/cmd/apply/options_test.go
  pkg/cmd/cmd.go
  pkg/cmd/meta/meta.go
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
  pkg/cmd/preview/preview.go
  pkg/cmd/preview/preview_test.go
Labels: kind/optimization

#1035 feat: generate cmd use terminal ui framework
  pkg/cmd/cmd.go
  pkg/cmd/generate/generate.go
Labels: kind/feature, area/cli

#1041 refactor: update delete cmd to follow the common cmd pattern
  pkg/cmd/build/build.go
  pkg/cmd/build/options.go
  pkg/cmd/cmd.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/destroy/destroy_test.go
  pkg/cmd/destroy/options.go
  pkg/cmd/destroy/options_test.go
  pkg/cmd/generate/builders/appconfig_builder.go
  pkg/cmd/generate/builders/appconfig_builder_test.go
  pkg/cmd/generate/builders/testdata/kcl.mod
  pkg/cmd/generate/generator/generator.go
Labels: kind/feature, area/cli

#1045 chore: delete useless signal handling logic
  pkg/cmd/destroy/destroy.go
  pkg/util/signals/signal.go
Labels: area/cli, kind/cleanup

#1052 fix: unexpected output in format byte slice
  pkg/cmd/generate/generate.go
Labels: kind/bug

#1053 chore: delete application field from Meta
  pkg/cmd/meta/meta.go
Labels: kind/cleanup

#1048 feat: add Extension api types
  pkg/apis/api.kusion.io/group.go
  pkg/apis/api.kusion.io/v1/resource.go
  pkg/apis/api.kusion.io/v1/types.go
Labels: kind/feature

#1065 feat: update kusion project and stack create
  pkg/cmd/project/create/options.go
  pkg/cmd/stack/create/options.go
Labels: kind/feature

#1061 feat: update implementation of terminal ui for kusion
  go.mod
  go.sum
  pkg/cmd/apply/apply.go
  pkg/cmd/apply/apply_test.go
  pkg/cmd/cmd.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/destroy/destroy_test.go
  pkg/cmd/generate/generate.go
  pkg/cmd/preview/preview.go
  pkg/cmd/preview/preview_test.go
  pkg/engine/api/apply.go
  pkg/engine/api/destroy.go
  pkg/engine/operation/models/change.go
  pkg/util/terminal/ui.go
  test/e2e/kusionctl_test.go
Labels: kind/feature

#1071 feat: update kusion destroy progressbar
  pkg/cmd/destroy/destroy.go
Labels: kind/feature

#1075 fix: workspace update defaults to use current workspace
  pkg/cmd/workspace/update/options.go
Labels: kind/bug

#1074 fix: add workdir to meta flag of kusion cli
  pkg/cmd/meta/meta.go
Labels: kind/bug

#1083 feat: remove server from root cmd
  pkg/cmd/cmd.go
Labels: kind/feature

#1085 test: restore e2e tests after updating modules
  test/e2e/kusionctl_test.go
Labels: ci/e2e
