Repository KusionStack/kusion, pull requests merged in 2024-06, with the labels that each got.

#1139 feat: optimize kusion apply with by default watching
  go.mod
  go.sum
  pkg/clipath/home_windows_test.go
  pkg/cmd/apply/apply.go
  pkg/cmd/apply/apply_test.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/destroy/destroy_test.go
  pkg/cmd/generate/generate.go
  pkg/cmd/mod/list.go
  pkg/cmd/preview/preview.go
  pkg/engine/api/apply.go
  pkg/engine/api/destroy.go
  pkg/engine/api/generate.go
  pkg/engine/operation/apply.go
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/operation/models/change.go
  pkg/engine/operation/models/operation_context.go
  pkg/engine/operation/watch.go
  pkg/engine/printers/table.go
  pkg/engine/release/util.go
  pkg/engine/runtime/kubernetes/kubernetes_runtime.go
  pkg/engine/runtime/runtime.go
  pkg/engine/runtime/terraform/terraform_runtime.go
  pkg/engine/util.go
  pkg/server/manager/stack/stack_manager.go
  pkg/util/pathutil/pathutil_windows.go
  pkg/util/pretty/prefix_printer.go
  pkg/util/pretty/prefix_text_printer.go
  pkg/util/pretty/prefix_text_printer_test.go
  pkg/util/pretty/spinner.go
  pkg/util/pretty/spinner_text.go
  pkg/util/pretty/style.go
  pkg/util/signal/signal.go
  pkg/util/signal/signal_posix.go
  pkg/util/signal/signal_windows.go
  pkg/util/terminal/ui.go
  pkg/util/terminal/ui_test.go
Labels: kind/feature

#1148 fix: set the release phase as failed when exit apply prompt
  pkg/cmd/apply/apply.go
Labels: kind/bug

#1149 feat: update the init and stack create scaffolding templates
  pkg/cmd/stack/util/util.go
  pkg/scaffold/quickstart/default/kcl.mod
  pkg/scaffold/quickstart/default/main.k
Labels: kind/feature

#1151 docs: update README.md for better readibility
  README.md
  docs/app_workflow.jpg
  docs/logo.png
  docs/overview.jpg
  docs/platform_workflow.jpg
Labels: kind/documentation

#1152 docs: update contributing guide
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/contributing.md
Labels: kind/documentation

#1157 fix: broken link of README.md
  README.md
Labels: kind/documentation

#1159 fix: broken slack link of README.md
  README.md
Labels: kind/documentation

#1175 fix: skip replacing secret data without ref prefix
  pkg/engine/operation/graph/resource_node.go
Labels: kind/bug

#1185 feat: support spec file as input of preview and apply
  pkg/apis/api.kusion.io/v1/types.go
  pkg/cmd/apply/apply.go
  pkg/cmd/preview/preview.go
Labels: kind/feature

#1189 feat: support path-style of bucket for s3 storage backend
  pkg/apis/api.kusion.io/v1/types.go
  pkg/backend/storages/s3.go
  pkg/config/validation.go
Labels: kind/feature

#1186 feat: support terraform resource import
  pkg/engine/operation/graph/resource_node.go
  pkg/engine/runtime/terraform/terraform_runtime.go
  pkg/engine/runtime/terraform/tfops/workspace.go
Labels: kind/feature

#1191 feat: support release unlock command
  pkg/cmd/cmd.go
  pkg/cmd/release/release.go
  pkg/cmd/release/release_test.go
  pkg/cmd/release/unlock.go
  pkg/cmd/release/unlock_test.go
  pkg/cmd/util/helpers.go
  pkg/engine/release/util.go
Labels: kind/feature

#1176 feat: mask secret data in preview result
  pkg/util/diff/diff.go
  pkg/util/diff/diff_test.go
Labels: kind/feature
