Repository KusionStack/kusion, pull requests merged in 2024-03, with the labels that each got.

#899 feat: workload generator add container dirs implementation
  pkg/modules/generators/workload/workload_generator.go
  pkg/modules/generators/workload/workload_generator_test.go
Labels: kind/feature, area/cli

#918 feat: add client for communicating with OCI repository
  go.mod
  go.sum
  pkg/oci/client/build.go
  pkg/oci/client/build_test.go
  pkg/oci/client/client.go
  pkg/oci/client/push.go
  pkg/oci/client/ref.go
  pkg/oci/client/testdata/artifact/deploy/repo.yaml
  pkg/oci/client/testdata/artifact/deployment.yaml
  pkg/oci/client/testdata/artifact/ignore-dir/deployment.yaml
  pkg/oci/client/testdata/artifact/ignore.txt
  pkg/oci/client/testdata/artifact/somedir/git/repo.yaml
  pkg/oci/client/testdata/artifact/somedir/repo.yaml
  pkg/oci/metadata/metadata.go
Labels: kind/feature

#843 feat: add generate cmd implementation
  go.mod
  go.sum
  pkg/cmd/build/build.go
  pkg/cmd/build/build_test.go
  pkg/cmd/build/builders/kcl/kcl_builder.go
  pkg/cmd/build/builders/kcl/kcl_builder_test.go
  pkg/cmd/build/builders/kcl/type.go
  pkg/cmd/build/builders/kcl/type_test.go
  pkg/cmd/build/builders/kcl/util.go
  pkg/cmd/build/options.go
  pkg/cmd/build/options_test.go
  pkg/cmd/build/util.go
  pkg/cmd/build/util_test.go
  pkg/cmd/cmd.go
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generate_test.go
  pkg/cmd/generate/generator/fake/fake.go
  pkg/cmd/generate/generator/generator.go
  pkg/cmd/generate/run/run.go
  pkg/cmd/generate/run/run_test.go
  pkg/cmd/generate/run/testdata/base/base.k
  pkg/cmd/generate/run/testdata/prod/kcl.mod
  pkg/cmd/generate/run/testdata/prod/main.k
  pkg/cmd/mod/mod_push.go
  pkg/cmd/util/helpers.go
  pkg/oci/client/push.go
  pkg/util/io/file.go
  test/e2e/kusionctl_test.go
Labels: kind/feature, area/cli

#953 feat: add spec storage and integrate with generate cmd
  pkg/backend/backend.go
  pkg/backend/storages/local.go
  pkg/backend/storages/mysql.go
  pkg/backend/storages/oss.go
  pkg/backend/storages/s3.go
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generator/generator.go
  pkg/engine/spec/storage.go
  pkg/engine/spec/storages/local.go
  pkg/engine/spec/storages/oss.go
  pkg/engine/spec/storages/s3.go
  pkg/engine/spec/storages/util.go
  pkg/scaffold/quickstart/dev/kcl.mod
Labels: kind/feature

#961 feat: build generator support darwin/arm64
  go.mod
  go.sum
  pkg/cmd/mod/mod_push.go
Labels: kind/feature

#962 feat: update module structure for mod push
  pkg/cmd/mod/mod_push.go
Labels: kind/bug

#964 feat: mod push add examples dir also mark generator executable
  pkg/cmd/generate/generator/generator.go
  pkg/cmd/mod/mod_push.go
  pkg/util/io/dir.go
  pkg/util/io/file.go
Labels: kind/feature

#977 fix: update preview&apply to use latest generator
  pkg/cmd/apply/options.go
  pkg/cmd/apply/options_test.go
  pkg/cmd/build/builders/kcl/kcl_builder.go
  pkg/cmd/build/util.go
  pkg/cmd/generate/generate.go
  pkg/cmd/generate/generate_test.go
  pkg/cmd/generate/run/run.go
  pkg/cmd/generate/run/testdata/base/base.k
  pkg/cmd/generate/run/testdata/prod/kcl.mod
  pkg/cmd/generate/run/testdata/prod/main.k
  pkg/cmd/preview/options.go
  pkg/cmd/preview/options_test.go
Labels: kind/bug, area/cli
