Repository KusionStack/kusion, pull requests merged in 2024-02, with the labels that each got.

#791 fix: add options sub-cmd for kusion
  pkg/cmd/cmd.go
Labels: kind/bug, kind/feature

#802 feat: preview auto shows diff details
  docs/cmd/en_US/kusion_apply.md
  docs/cmd/en_US/kusion_destroy.md
  docs/cmd/en_US/kusion_preview.md
  pkg/cmd/apply/apply.go
  pkg/cmd/destroy/destroy.go
  pkg/cmd/preview/preview.go
Labels: area/cli

#803 feat: add code runner for configuration code execution
  pkg/cmd/generate/run/fake/fake.go
  pkg/cmd/generate/run/run.go
  pkg/cmd/generate/run/run_test.go
  pkg/cmd/generate/run/testdata/base/base.k
  pkg/cmd/generate/run/testdata/prod/kcl.mod
  pkg/cmd/generate/run/testdata/prod/main.k
  pkg/cmd/generate/run/testdata/prod/stack.yaml
  pkg/cmd/generate/run/testdata/project.yaml
Labels: kind/feature

#804 feat: add crd resource visitor util
  pkg/cmd/util/resource/crd/multi_crd.yaml
  pkg/cmd/util/resource/crd/webapp_crd.yaml
  pkg/cmd/util/resource/visitor.go
  pkg/cmd/util/resource/visitor_test.go
Labels: kind/feature

#819 fix: term.GetTerminalWidth failed on windows
  third_party/dyff/output_human.go
  third_party/term/term.go
Labels: kind/bug, area/cli

#814 fix: use package path/filepath instead of path to support windows
  pkg/cmd/build/builders/kcl/kcl_builder.go
  pkg/cmd/workspace/util/util_test.go
  pkg/engine/backend/config.go
  pkg/engine/backend/util_test.go
  pkg/engine/states/local/filesystem_state.go
  pkg/engine/states/local/filesystem_state_test.go
  pkg/util/kfile/file.go
  pkg/workspace/operator.go
  pkg/workspace/operator_test.go
Labels: kind/bug, area/cli

#817 fix: no assignment of releaseVersion when version in buildInfo is empty
  pkg/version/types.go
Labels: kind/bug, area/cli
